#!bin/bash
read -p "Enter three numbers:" num1 num2 num3
if test $num1 -gt $num2 && test $num1 -gt $num3
then 
	echo "$num1 is greater"
elif test $num2 -gt $num3
then
	echo "$num2 is greater"
else
	echo "$num3 is greater"
fi
